// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#ifndef UI_SCREEN_H
#define UI_SCREEN_H
#include<lvgl.h>


extern lv_obj_t * main_screen;
extern lv_timer_t *timer_fresh;
extern lv_group_t  *main_screen_group;

void gui_screen_init(void);


#endif


