// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project
#include <Arduino.h>
#include <lvgl.h>
#include "gui.h"
#include "gui_Screen.h"
#include "systemData.h"
#include "gui_countDown_thresh.h"
#include "gui_pressure_thresh.h"
#include "gui_pressure_display.h"
#include "gui_statusBar.h"
#include "gui_quality_display.h"


lv_obj_t * main_screen = NULL;
lv_group_t  *main_screen_group;//屏幕按键控制组
lv_timer_t *timer_fresh;//变量刷新定时器


/**------------------------------------------------事件回调函数--------------------------------------------**/ 
// 定时器回调函数
static void timer_fresh_cb(lv_timer_t *timer) 
{ 
    //wifi信号质量刷新
    gui_wifi_fresh();
    //电池电量刷新
    gui_battery_fresh();
    //倒计时阈值刷新
    gui_count_down_fresh();
    //压力阈值刷新
    gui_pressure_thresh_refresh();
    //质量传感器
    gui_quality_display_refresh();
    //压力传感器
    gui_pressure_display_refresh();
    //时间刷新
    gui_time_fresh();
}


void gui_screen_init(void)
{
    //-----------------------------------------创建主屏幕-------------------------------------//
    main_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(main_screen, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(main_screen, lv_color_make(0,0,0),0);
    //--------------------------------------创建状态栏----------------------------------------//
    gui_statusBar_create(main_screen);
    //------------------------------------创建压力阈值编辑器----------------------------------//
    gui_pressure_thresh_editor_init(main_screen);
    //------------------------------------创建时间阈值编辑器----------------------------------//
    gui_countDown_thresh_init(main_screen);
    //------------------------------------创建数值显示器-------------------------------------//
    gui_quality_display_create(main_screen);
    //-------------------------------------创建压力曲线-------------------------------------//
    gui_pressure_display_create(main_screen);

    //按键控制组创建
    main_screen_group = lv_group_create();
    lv_group_add_obj(main_screen_group,pressure_thres_editor.cont);
    lv_group_add_obj(main_screen_group,count_down_editor.cont);
    //定时器创建
    timer_fresh = lv_timer_create(timer_fresh_cb, 250, NULL);
}

